#!/usr/bin/env bash
# This script displays information about subdomains

dns_config() {
    script=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $script" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [[ "$#" == 1 ]]; then
    domain="$1"
    subdomains=("www" "lb-01" "web-01" "web-02")

    for subdomain in "${subdomains[@]}"; do
        dns_config "$domain" "$subdomain"
    done
elif [[ "$#" == 2 ]]; then
    domain="$1"
    subdomain="$2"
    dns_config "$domain" "$subdomain"
else
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi
