#!/usr/bin/env bash
# This script transfers a file from a client to a server:
# Requirements:
# -Accepts 4 parameters
# -The path to the file to be transferred
# -The IP of the server we want to transfer the file to
# -The username scp connects with
# -The path to the SSH private key that scp uses
# -Display Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY if less than 3 parameters passed
# -scp must transfer the file to the user home directory ~/
# -Strict host key checking must be disabled when using scp

if [ "$#" -gt 3 ]; then
	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~/
elif [ "$#" -gt 2 ]; then
	scp -o StrictHostKeyChecking=no "$1" "$3@$2":~/
else
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
