#!/usr/bin/env bash
# Installs web server
# Requirements:
# 1. Nginx should be listening on port 80
# 2. When querying Nginx at its root / with a GET request
#    (requesting a page) using curl, it must return a page 
#    that contains the string Hello World!
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'nginx http'
sudo ufw reload
echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
