#!/usr/bin/env bash
# Installs web server
# Requirements:
# 1. Nginx should be listening on port 80
# 2. When querying Nginx at its root / with a GET request
#    (requesting a page) using curl, it must return a page 
#    that contains the string Hello World!
# 3. /redirect me redirects to another page
#sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'nginx http'
sudo ufw reload
sudo chmod 755 -R /var/www/html
echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	location / {
		try_files $uri $uri/ =404;
	}
	location /redirect_me {
        	return 301 https://google.com;
    	}
}
" > /etc/nginx/sites-available/default
sudo service nginx restart
