#!/usr/bin/env bash
# Installs web server
# Requirements:
# 1. Nginx should be listening on port 80
# 2. When querying Nginx at its root / with a GET request
#    (requesting a page) using curl, it must return a page 
#    that contains the string Hello World!
# 3. /redirect me redirects to another page
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'nginx http'
sudo ufw reload
sudo chown -R ubuntu:ubuntu /var/www/html/
echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
sudo echo "location /redirect_me {" | sudo tee /etc/nginx/conf.d/redirect.conf > /dev/null
sudo echo "    return 301 https://github.com/m453h;" | sudo tee -a /etc/nginx/conf.d/redirect.conf > /dev/null
sudo echo "}" | sudo tee -a /etc/nginx/conf.d/redirect.conf > /dev/null
sudo service nginx restart
