#!/usr/bin/env bash
# Installs and configures HAproxy
sudo apt-get update
sudo apt-get -y install haproxy
echo "
defaults
		mode http
		no option http-use-htx
frontend http-incoming
        bind *:80
        mode http
        default_backend my-webservers
backend my-webservers
        balance roundrobin
        server 197844-web-01 54.157.179.66:80 check
        server 197844-web-02 54.236.28.100:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
