#!/usr/bin/env bash
# This script is displaying a list of currently running processes
# It show all processes, for all users, including those which might not have a TTY
# It displays in a user-oriented format and shows the process hierarchy

ps auxf