#!/usr/bin/env bash
# This script is Creating the file /var/run/myscript.pid containing its PID
# Displaying To infinity and beyond indefinitely
# Displaying I hate the kill command when receiving a SIGTERM signal
# Displaying Y U no love me?! when receiving a SIGINT signal
# Deleting the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

echo $$ >> /var/run/myscript.pid

trap "echo 'I hate the kill command'; rm -rf /var/run/myscript.pid; exit" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm -rf /var/run/myscript.pid; exit" SIGQUIT

while true
do 
    echo 'To infinity and beyond' 
    sleep 2
done