#!/usr/bin/env bash
# This script is To infinity and beyond indefinitely With a sleep 2 in between each iteration
# and I am invincible!!! when receiving a SIGTERM signal

trap 'echo "I am invincible!!!"; exit' SIGTERM
while true
do
    echo "To infinity and beyond"
    sleep 2
done