#!/usr/bin/env bash
# This script is writting I am alive! indefinitely to the file /tmp/my_process
# with 2 seconds pause in between iterations

while true
do
  echo "I am alive!" >> /tmp/my_process
  sleep 2
done