#!/usr/bin/env bash
# This script is displaying the content of the file /etc/passwd.
# It is only displaying the username, user id, and user home directory path.

while read -r passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
