#!/usr/bin/env bash
# This script is displaying the visitor IP along with the 
# HTTP status code from the Apache log file.
# The script groups visitors by IP and HTTP status code, and displays this data in the
# OCCURENCE_NUMBER IP HTTP_CODE
awk '{ arr[$1 " " $9]++ } END { for (i in arr) print arr[i], i }' apache-access.log | sort -rn 