#!/usr/bin/env bash
# This script is displaying the time for 12 hours and 59 minutes

hr_counter=0

while [ $hr_counter -lt 13 ]; do
  echo "Hour: "$hr_counter
  
  ((hr_counter++))
  
  min_counter=1
  
  while [ $min_counter -lt 60 ]; do
    echo $min_counter
    
    ((min_counter++))
  done

done
