#!/usr/bin/env bash
# This script is displaying the content of the current directory
# in a list format Where only the part of the name after 
# the first dash is displayed (refer to the example).

files=$(ls)
for file in $files; do
  echo "$file" | cut -d- -f2
done
