#!/usr/bin/env bash
# This script runs the whoami command under the user passed as an argument
# It works for different users, Usage: ./0-iamsomeoneelse <user>
if [ -z "$1" ]; then
  echo "Usage: $0 <user>"
  exit 1
fi

sudo -u "$1" whoami	
